apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vote-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: vote
 updatePolicy:
    updateMode: "Auto" # Options: "Off", "Initial", "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: '100m'
          memory: '256Mi'
        maxAllowed:
          cpu: '2'
          memory: '4Gi'
        controlledValues: RequestsAndLimits 
